---
title: "Single Polyp Stats"
author: "Shayle Matsuda"
date: "10/28/2021"
output:
  pdf_document: default
  word_document: default
  html_document: 
    self_contained: no
editor_options:
  chunk_output_type: console
---
data analysis for single polyp metabolomics

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
```

# libraries
```{r,echo=FALSE}  
# knitr::opts_chunk$set(warning=FALSE, message=FALSE)
library(ape)
library(MuMIn)
library(plyr) 
library(dplyr)
library(ggplot2)
library(ggpubr)
library(lmerTest)
library(car)
library(emmeans)
library(gridExtra)
library(multcomp)
library(reshape)
library(tidyverse)
library(factoextra)
library(reshape2)
library(vegan) 
library(pairwiseAdonis)
library("scales")
packageVersion("scales")
library(RColorBrewer)
library(colorRamps)
library(devtools)
library(phyloseq)
library(readr)
library(microbiome)
library(vegan)
```

Load in data:
```{r}
mData<-read.csv("single polyp master with PCoA coordinates.csv") #metabolomics data and xy coords from Ty
mData$ATTRIBUTE_Sample_Name<-as.factor(as.character(mData$ATTRIBUTE_Sample_Name))
mData$ATTRIBUTE_Colony_number<-as.factor(as.character(mData$ATTRIBUTE_Colony_number))
mData<-subset(mData, ATTRIBUTE_Colony_number!="976B")#remove dup

```
# PERMANOVA
```{r}
#PERMANOVA
mData.sd<-mData[,1:11] #metadata
mData.meta<-mData[,12:566] #metabolomics data

####################### Between colonies and Between Sample points

# Bray-Curtis distance 
mData.dist <- vegdist(mData[,12:566],  method = "bray")
mData.dist.mat<-as.matrix(mData.dist)

PCOA <- pcoa(mData.dist) #pcoa
barplot(PCOA$values$Relative_eig[1:10]) # plot the eigenvalues 
biplot.pcoa(PCOA) #plot
PCOAaxes <- PCOA$vectors[,c(1,2)] #for visualization only

mData.dist2<-as.matrix(mData.dist)

 mData.dist.sd<- inner_join(rownames_to_column(mData.sd), rownames_to_column(data.frame(PCOAaxes)), type = "right", by = "rowname") #merge PCOAaxes and metadata
BetweenColonies_plot<-ggplot(mData.dist.sd, aes(x = Axis.1, y = Axis.2)) + 
  geom_point(aes(colour = Symbiont.Type), size = 4) +
  #scale_color_manual(values=Sp.colors)+
  #geom_text(label = rownames(scores), nudge_x = 0.05, nudge_y = 0.05,check_overlap = T) +
 # stat_ellipse(aes(x = Axis.1, y = Axis.2, colour = ATTRIBUTE_Colony_number), linetype = 2) +
  ggtitle("PCoA Between Colonies") +
  theme_classic();BetweenColonies_plot
 
############ plot Between colonies ####

BetweenColonies_plot<-ggplot(mData.dist.sd, aes(x = Axis.1, y = Axis.2)) + 
  geom_point(aes(colour = ATTRIBUTE_Colony_number), size = 4) +
  ggtitle("PCoA Between Colonies") +
  theme_classic();BetweenColonies_plot
       
#PERMANOVA between COLONIES
set.seed(30)
adonis2(mData.dist~ATTRIBUTE_Colony_number, data=mData.sd)

############# Between Sampling areas (polyps) ########
set.seed(30)
adonis2(mData.dist~Area, data=mData.sd)

mData.sd$PolypZone2<-mData.sd$Area #duplicate col
mData.sd$PolypZone2[mData.sd$PolypZone2 == "Touching 1"] <- "Base"
mData.sd$PolypZone2[mData.sd$PolypZone2 == "Touching 2"] <- "Base"
mData.sd$PolypZone2[mData.sd$PolypZone2 == "Midle 1"] <- "Mid"
mData.sd$PolypZone2[mData.sd$PolypZone2 == "Midle 2"] <- "Mid"

adonis2(mData.dist~PolypZone2, data=mData.sd)

mData.sd$Area[mData.sd$Area == "Base"] <- "1"
mData.sd$Area[mData.sd$Area == "Touching 1"] <- "2"
mData.sd$Area[mData.sd$Area == "Touching 2"] <- "3"
mData.sd$Area[mData.sd$Area == "Midle 1"] <- "4"
mData.sd$Area[mData.sd$Area == "Midle 2"] <- "5"
mData.sd$Area[mData.sd$Area == "Tip"] <- "6"

adonis2(mData.dist~Area*ATTRIBUTE_Colony_number, data=mData.sd)
adonis2(mData.dist~ATTRIBUTE_Colony_number*ATTRIBUTE_Branch_Letter*Area, data=mData.sd)
adonis2(mData.dist~ATTRIBUTE_Branch_Letter*Area, data=mData.sd)

#Plot: No patterns
BetweenSampArea_plot<-ggplot(mData.dist.sd, aes(x = Axis.1, y = Axis.2)) + 
  geom_point(aes(colour = Area), size = 4) +
  ggtitle("PCoA Between Sampling Area") +
  theme_classic();BetweenSampArea_plot

```

#Spatial autocorr stats
Within a branch, physical dist vs dist matrix dists, then run mantel to look for correlation.
```{r}
#create dist matrix with physical and bc dist (in excel)
Dist.compare.df<-read.csv("distances.csv")

#run pearson correlation 
library(ggpubr)
ggqqplot(Dist.compare.df$bc.dist, ylab = "bc.dist")
# wt
ggqqplot(Dist.compare.df$physical.dist, ylab = "physical.dist")
cor(Dist.compare.df$bc.dist, Dist.compare.df$physical.dist, method = c("pearson")) # 0.1669614 = corr 

#coeefficient Pearsons
cor.test(Dist.compare.df$bc.dist, Dist.compare.df$physical.dist, method = c("pearson"))

#coeefficient Pearsons rank-based bc no normal
cor.test(Dist.compare.df$bc.dist, Dist.compare.df$physical.dist, method = c("kendall"))

Dist.compare.df$col.branch<-paste(Dist.compare.df$Coral, Dist.compare.df$Branch)

Dist.compare.df$PolypZones<-as.factor(Dist.compare.df$PolypZones)

Dist.compare.df$PolypZones <- factor(Dist.compare.df$PolypZones, levels = c("Base", "Base-4", "4_5", "Base-5", "5_6","4_6", "Base-6"))


quantiles_95 <- function(x) {
  r <- quantile(x, probs=c(0.05, 0.25, 0.5, 0.75, 0.95))
  names(r) <- c("ymin", "lower", "middle", "upper", "ymax")
  r
}

ggplot(Dist.compare.df, aes(x=bc.dist, y=PolypZones, fill=PolypZones)) +
    guides(fill=F) +
    coord_flip() +
    stat_summary(fun.data = quantiles_95, geom="boxplot")

```

Figure 1H (stats)
```{r}
Dist.compare.df$Coral<-as.factor(as.character(Dist.compare.df$Coral))
mod<-lmer(bc.dist~physical.dist + (1|Coral) + (1|Coral:Branch), data=Dist.compare.df )
anova(mod)
  
ggqqplot(Dist.compare.df$bc.dist, ylab = "bc.dist")
ggqqplot(Dist.compare.df$physical.dist, ylab = "physical.dist")

### By polyp zones FIG1H #########
mod<- lmer(bc.dist~PolypZones + (1|Coral/Branch) , data=Dist.compare.df )
anova(mod)
summary(mod)
r.squaredGLMM(mod)
qqPlot(residuals(mod)) # looks good

#use this non-parametric Kruskal-Wallis test
kruskal.test(bc.dist ~ PolypZones, data = Dist.compare.df)
pairwise.wilcox.test(Dist.compare.df$bc.dist_sqrt, Dist.compare.df$PolypZones,
                 p.adjust.method = "BH")

```

